version: '3.3'

services:
  toDoDb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'spring_to_do_database'
      MYSQL_USER: 'to_do_application_user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - '3308:3306'

    expose:
      - '3306'

    volumes:
      - spring-to-do-DB:/var/lib/mysql

volumes:
  spring-to-do-DB: